### ISSUE TITLE
MIssing header file

### ISSUE THREAD

**Issue by RandyLBryant** [desbma/sacad#101]
I am trying to build and install sacad on Mac OS 11.6.8 using python 3.12.6 and I am getting the following error:

  self.initialize_options()
aiohttp/_websocket.c:196:12: fatal error: 'longintrepr.h' file not found
  #include "longintrepr.h"
           ^~~~~~~~~~~~~~~

**Comment by desbma** [comment]
It seems unrelated to sacad, try searching and/or asking on the aiohttp project: https://github.com/aio-libs/aiohttp/issues
