### ISSUE TITLE
sacad_r can not find results for soundtracks or compilation albums with Various as the album artist

### ISSUE THREAD

**Issue by squatchgit** [desbma/sacad#103]
I have my library setup with Artist = song artist, Album Artist = Album Artist,  Ablum = Album Name.  

So for example I have the song "Keep on Lovin' You" by "Steel Magnolia" on the album "Valentine’s Day: Original Motion Picture Soundtrack" and the Album Artist is "Various".  

When I run sacad_r -f /Music 600 + -t 50 

I am not able to find the cover, it has a message like:

sacad_r: Unable to find cover for 'Valentine’s Day: Original Motion Picture Soundtrack' by 'Steel Magnolia' from '/Music/Various /Valentine_s Day_ Original Motion Picture Soundtrack/15 - Steel Magnolia - Keep on Lovin_ You.mp3'

I have no way to tell it to search for Album Artist, if you go to discogs.com and search for the artist and the album title you of course get no results.  If I use the advanced search and search for Title/Name "Valentine’s Day: Original Motion Picture Soundtrack" and Artist "Various" you of course do find the results with covers even if you add Track Title "Keep on Lovin' You". 

It seems like it should be automatically defaulting the search for Artist as the Album Artist if that value is populated, or at least have an option to do so when it is not blank, or search first by one and then the other?

**Comment by desbma** [comment]
Could you upload a single song here that has both "artist" and "album artist" tag values set, so I can look at the tag handling?

**Comment by squatchgit** [comment]
[example.zip](https://github.com/user-attachments/files/17467109/example.zip)
Here is an example

**Comment by desbma** [comment]
Fixed in 6e66fe380d3eb604e7f8dda2733bce3402a4e517
