### ISSUE TITLE
Not handling spaces properly

### ISSUE THREAD

**Issue by tcwota** [desbma/sacad#14]
In either Windows standalone or using Python in Windows, a space in the directory or album search returns an error. For instance, even using the Master of Puppets example script returns this:

sacad: error: argument size" invalid int value: 'of'

or, performing a sacad_r for a directory of "c:\mp3\LCDSoundsystem" works fine, but "c:\mp3\LCD Soundsystem" returns the above error with invalid int value 'Soundsystem'

**Comment by desbma** [comment]
Can you please paste here the exact command line you are using that cases the error?

**Comment by tcwota** [comment]
Sure, here you go:

![sacad](https://user-images.githubusercontent.com/33274176/32278271-2bbf4b70-bee3-11e7-9976-2cbae0e46857.jpg)

The program does a PHENOMENAL job when there are no spaces in the search term or directory name! Fantastic work!

**Comment by desbma** [comment]
I think this is a quoting issue with the `’` character. Try using the `'` or `"` character instead around expressions with spaces, and it should work.

**Comment by tcwota** [comment]
I confirm that it is the ’ character. Using double quotes does indeed work (the default quotes of a Windows command prompt). One problem is that there is no way to make a straight single quote in the command prompt, so I would recommend changing your example script on the main page to using double quotes instead of single quotes to avoid the confusion.

Thanks for the quick response and the awesome program!

**Comment by desbma** [comment]
OK, I followed your advice and changed the example.
