### ISSUE TITLE
How to embed artwork into mp3/flac?

### ISSUE THREAD

**Issue by DasHammett** [desbma/sacad#15]
Hi, 

I cannot seem to find the option to embed the artwork into the mp3/flac files. I have not seen the option in the documentation either.

Thanks

EDIT: 
Replacing cover name by "+" renders the following error message:
`Unable to guess image format from extension, or unknown format:`
Using SACAD version 2.0.6

**Comment by desbma** [comment]
Hello,

`sacad` can not embed cover directly into a file, it can only download to an image file.

`sacad_r` can analyze a directory tree recursively, find audio files, download missing covers, and embed them into audio files, if you use `+` as its third parameter.
For example, to search, download, and embed ~600x600 covers for all audio files in `my_music_directory`: `sacad_r my_music_directory 600 +`

**Comment by DasHammett** [comment]
Hello, 

Thanks for the clarification! Works as expected :)

Closing question.

Kind regards

**Comment by oscar230** [comment]
Thanks for the help @desbma :)
