### ISSUE TITLE
Install issue 

### ISSUE THREAD

**Issue by lbrth** [desbma/sacad#16]
Hello,

I have some problem to install sacad. here the output after running the commande `python3 sacad -h` : `ImportError : no module named _lzma`.

I tried to manualy install this library but seems to be doesn't exist.

Do you have an idea ? 

I'm on Linux/Debian

**Comment by desbma** [comment]
Hi,

* How did you install sacad? From source? with pip?
* What is your Python version? (output of `python3 --version`)
* How did you run sacad? The command you give (`python3 sacad -h`) is invalid as such, and can not work anyway (it will not run any sacad code)

**Comment by lbrth** [comment]
Hi,

- Both, I tried first to install by pip. Pip3 never working on my linux so I had to do : `python3 -m pip install sacad`and the installation was successful. 

- Python 3.5.1 and python 2.7.12

- I run  the commande `sacad -h` I have a `command not found`, so I did `python3 sacad -h`. Most of the time if I don't precise the python version before the script name, by default it's the python2 which running and not the python3 and/or I have a `command not found` . By the way I don't konw yet how to change this setting.
 
Thank for your help !

**Comment by desbma** [comment]
> I run the commande sacad -h I have a command not found

Something seems seriously wrong with your installation. 
Just `sacad` should work and use the `python3` interpreter automatically. The command `python3 sacad` instructs python to run the sacad script in your current directory (I bet there is none, unless you changed directory to where it was installed) so that can **not** work.

Can you please post here the output of:
* `which pyhon3`
* `which sacad`
* `python3 -m sacad`
* `python3 -c 'import sacad; print(sacad.__version__)'`

**Comment by lbrth** [comment]
- `which python3`: `/usr/local/bin/python3``

- `which sacad`: there is nothing as output, that really weird 

- `python3 -m sacad`: `/usr/local/bin/python3: Error while finding spec for 'sacad.__main__' (<class 'ImportError'>: No module named '_lzma'); 'sacad' is a package and cannot be directly executed`

- `python3 -c 'import sacad; print(sacad.__version__)`: 
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/sacad/__init__.py", line 17, in <module>
    from sacad import sources
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/sacad/sources/__init__.py", line 1, in <module>
    from sacad.sources.amazoncd import AmazonCdCoverSource, AmazonCdCoverSourceResult
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/sacad/sources/amazoncd.py", line 8, in <module>
    from sacad.cover import CoverImageFormat, CoverImageMetadata, CoverSourceQuality, CoverSourceResult
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/sacad/cover.py", line 19, in <module>
    import web_cache
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/web_cache/__init__.py", line 12, in <module>
    import lzma
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/lzma.py", line 26, in <module>
    from _lzma import *
ImportError: No module named '_lzma'`

**Comment by desbma** [comment]
How did you install Python 3?
Your install is missing the lzma module, which should be included in all Python versions after 3.3.
If you are on Debian, you should install it from the official repositories, and the issue will go away.
The following command should not show any error for a sane Python installation: `python -c 'import lzma'`.

**Comment by lbrth** [comment]
Hi,

Python3 is installed as package published by Synology NAS, may be this installation is not complete for some unknowing reason. I will check that asap. If the package provided by Synology is not complete I will removed it and then  reinstall it all from official repositories. 

Thank a lot for your help,

**Comment by desbma** [comment]
I'm closing this then, since the problem seems to be coming from your Python installation.
