### ISSUE TITLE
libgcc_s.so.1 must be installed for pthread_cancel to work

### ISSUE THREAD

**Issue by Micha-Btz** [desbma/sacad#18]
Hey there,

I want to add covers to my collection, but the brogram aborted really quick.
Can you please take a look?

```
sacad_r flac/ -a de -d 600 AlbumArt.jpg
client_session: <aiohttp.client.ClientSession object at 0x7fcb61d3f908>
2018-03-13 19:28:27,320 15506 MainThread: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fcb61d3f748>
2018-03-13 19:28:27,320 15506 MainThread: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fcb61d3f5c0>
2018-03-13 19:28:27,320 15506 MainThread: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fcb61d3fb00>
libgcc_s.so.1 must be installed for pthread_cancel to work
libgcc_s.so.1 must be installed for pthread_cancel to work
Aborted
```

> root@sysiphus:~# dpkg -S libgcc_s.so.1
> libx32gcc1: /usr/libx32/libgcc_s.so.1
> libx32gcc-7-dev: /usr/lib/gcc/x86_64-linux-gnu/7/x32/libgcc_s.so.1
> libgcc1:amd64: /lib/x86_64-linux-gnu/libgcc_s.so.1
> lib32gcc-7-dev: /usr/lib/gcc/x86_64-linux-gnu/7/32/libgcc_s.so.1
> libgcc-6-dev:amd64: /usr/lib/gcc/x86_64-linux-gnu/6/libgcc_s.so.1
> libx32gcc-6-dev: /usr/lib/gcc/x86_64-linux-gnu/6/x32/libgcc_s.so.1
> libgcc1:i386: /lib/i386-linux-gnu/libgcc_s.so.1
> libgcc-8-dev:amd64: /usr/lib/gcc/x86_64-linux-gnu/8/libgcc_s.so.1
> libgcc-7-dev:amd64: /usr/lib/gcc/x86_64-linux-gnu/7/libgcc_s.so.1
> lib32gcc-6-dev: /usr/lib/gcc/x86_64-linux-gnu/6/32/libgcc_s.so.1
> lib32gcc1: /usr/lib32/libgcc_s.so.1
Debian unstable 
Debian 4.15.4-1 (2018-02-18) x86_64 GNU/Linux
```
dpkg -l libc6
ii  libc6:amd64                          2.27-2                  amd64                   GNU C Library: Shared libraries
ii  libc6:i386                           2.27-2                  i386                    GNU C Library: Shared libraries
```

If you need more information, please tell me.

thanks Micha

**Comment by desbma** [comment]
It looks like an issue with you Debian installation. You have several versions of the same library with at least 3 different architectures (i386, x32 and x86_64). I would try to remove most of them except `libgcc1`.
