### ISSUE TITLE
AssertionError on Windows using sacad_r

### ISSUE THREAD

**Issue by desbma** [desbma/sacad#20]
Issue from https://github.com/desbma/sacad/issues/13#issuecomment-409701982

> Hi :)
> I'm getting this:
> 
> Searching covers: 0%| | 1/2929 [00:01<1:12:20, 1.48s/ covers, ok=0, errors=1, no result found=0]
> Traceback (most recent call last):
> File "C:\Python36\lib\site-packages\cx_Freeze\initscripts_startup_.py", line 14, in run
> File "C:\Python36\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
> File "sacad\recurse.py", line 320, in
> File "sacad\recurse.py", line 316, in cl_main
> File "sacad\recurse.py", line 267, in get_covers
> File "C:\Python36\lib\asyncio\base_events.py", line 467, in run_until_complete
> File "sacad\recurse.py", line 210, in update_progress
> File "Z:\data\Projets\Sacad\sacad_init_.py", line 46, in search_and_download
> File "Z:\data\Projets\Sacad\sacad\sources\base.py", line 92, in search
> File "Z:\data\Projets\Sacad\sacad\cover.py", line 306, in updateImageMetadata
> File "Z:\data\Projets\Sacad\sacad\cover.py", line 322, in setSizeMetadata
> AssertionError
> 
> I ran the script like this - sacad_r D:\iTunes 500 AlbumArt.jpg - and it got 11% through my library and then it crashed with the above message. When trying to rerun the script with -i added, it makes the same error, but immediately, so I'm thinking that it has met something at a certain place in my library that it dislikes..?
> 
> Cheers,
> Jon :)

**Comment by desbma** [comment]
@jonlanghoff
Is possible for you to run `sacad_r` on subdirectories, to narrow it down to a single album that causes the issue ?

**Comment by desbma** [comment]
With the example you have pasted above, it seems the error occurs immediately, so maybe if you pick the first album of the first artist, the error will occur?

If it does, then you can give me the value of the "artist" and "album" tags of the first audio file of the album so I can reproduce the issue on my computer.

If that does not work, I can generate a special version for you with more output to investigate the issue, but I would prefer not to do that if I can.

**Comment by jonlanghoff** [comment]
Hi Desbma,
No, there are too many, so I scripted a solution instead where I started your app once for each folder.  I didn't save the output, but it solved my issue, so I'm happy!
B.r. Jon

**Comment by desbma** [comment]
Ok, if you happen to find the "artist" / "album" pair that causes the error, please reopen this issue then.

**Comment by mxmilkb** [comment]
I did an strace of the problem happening and stuck the last few percent of it in [this](https://gist.github.com/mxmilkb/af0c66d54afe7285717ef39730be7d31) gist.

**Comment by desbma** [comment]
@mxmilkb 
I presume you are on Linux, so please open another issue with the full output, and your Python and Sacad version.

**Comment by desbma** [comment]
I think I've fixed it.

It turns out it was what recently caused the automated tests to fail.
