### ISSUE TITLE
Feature request: verbose mode

### ISSUE THREAD

**Issue by mxmilkb** [desbma/sacad#22]
So I can figure out what is causing #20 :)

**Comment by desbma** [comment]
`sacad` already has a `-v` switch so I assume you are asking about `sacad_r`.

With asyncio the program is potentially doing hundreds of small unrelated things (coroutines) sequentially and having a verbose logging output would not help at all to understand what is going on.

Currently fatal errors are logged with a stack trace, and non fatal ones are logged at the end, so I believe this is enough.
