### ISSUE TITLE
Sacad not adding embedded cover art

### ISSUE THREAD

**Issue by newzealandpaul** [desbma/sacad#29]
I am running like this:

sacad_r -i directory 800 "+"

It seems to find cover art, but does not add it to the mp3 files. 

Any idea what I am doing wrong?

**Comment by desbma** [comment]
Please provide: 
* the version of Sacad you are using, and how you have installed it
* the full output of your command with `-v debug` added

**Comment by newzealandpaul** [comment]
I was wrong, it is tagging the MP3 files but for some reason apps are not reading the tags. Rewriting the tags with the MP3Tag app works and solves my problem.

**Comment by desbma** [comment]
Allright, I'm closing this then.
