### ISSUE TITLE
Improve Amazon Digital Music Sliced Images Joining Policy

### ISSUE THREAD

**Issue by baoshan** [desbma/sacad#3]
Great project, thanks again. I hope you could look at this:

`sacad "Alice Sara Ott" "Pictures" 1400 output.jpg`

The joined image has a black (right and bottom) border, (the original sliced images is not equal sized).

:cool:

**Comment by desbma** [comment]
Thanks for the report.

It is fixed in version 1.6.4 which should be published in few minutes.

**Comment by baoshan** [comment]
That's wonderful!
