### ISSUE TITLE
sasacd_r not reading album directory metadata

### ISSUE THREAD

**Issue by mbranton** [desbma/sacad#31]
when i run sacad_r on a directory containing directories that hold .flac files containing the tracks of albums, i get "Unable to read metadata for album directory". For example,
/usr/local/bin/sacad_r . 600 cover.jpg
sacad_r: Unable to read metadata for album directory './Magical Mystery Tour'         
sacad_r: Unable to read metadata for album directory './Let It Be Naked'                   
sacad_r: Unable to read metadata for album directory './The Beatles White Album'           
sacad_r: Unable to read metadata for album directory './Rubber Soul'                       
sacad_r: Unable to read metadata for album directory './Sgt Peppers Lonely Hearts Club Band'
sacad_r: Unable to read metadata for album directory './Revolver'                          
sacad_r: Unable to read metadata for album directory './Anthology 2 Disc 2'                
sacad_r: Unable to read metadata for album directory './Anthology 3 Disc 2'                
sacad_r: Unable to read metadata for album directory './Anthology 3'                        
sacad_r: Unable to read metadata for album directory './Yellow Submarine'                   
sacad_r: Unable to read metadata for album directory './Anthology 2'                          
sacad_r: Unable to read metadata for album directory './The Beatles Anthology 1 Disc 2'       
sacad_r: Unable to read metadata for album directory './A Hard Days Night'                    
sacad_r: Unable to read metadata for album directory './Help'                                 
sacad_r: Unable to read metadata for album directory './Anthology 1'                          
sacad_r: Unable to read metadata for album directory './Let It Be'                            
sacad_r: Unable to read metadata for album directory './Abbey Road'                           
sacad_r: Unable to read metadata for album directory './Love'  

But if i run sacad within any one of these directories, for example

cd Let\ It\ Be/;sacad "The Beatles" "Let It Be" 600 cover.jpg

that works of course. mutagen-inspect  on any of the .flac files produces the expected information, and printing out artist and album info that recurse.py gathers shows that this info is being gotten as well.

**Comment by desbma** [comment]
This is likely the same issue as https://github.com/desbma/sacad/issues/30.
Its already fixed, but not yet in a release because I am having trouble with the reliability of the Amazon cover sources.

If you want the fix, [install from source](https://github.com/desbma/sacad#from-source), otherwise you will have to wait the next release.

**Comment by desbma** [comment]
2.2.3 is released.
