### ISSUE TITLE
sacad_r: take into account all images found in the album directory

### ISSUE THREAD

**Issue by maszaa** [desbma/sacad#32]
Let's say I have defined 'Folder.jpg' as the image name but some of my files have embedded cover arts, some album folders have 'Folder.png' and some have 'Artist - Album.jpg'. Would be nice if there would be for example a command line argument to include all these cover images when determining if a covert art exists already.

**Comment by desbma** [comment]
Sacad only supports library which are tagged and organized with consistent conventions, and I do not intend to change this.

However with a bit of scripting I should be possible for you to rename all images to have a similar name, remove all embedded overs (or embed them all), etc.
