### ISSUE TITLE
Finding non-square covers

### ISSUE THREAD

**Issue by maddhin** [desbma/sacad#34]
Hi,
I try to get a larger number of non-square covers (usually 800x1200) - actually old music tape covers which I use to print out RFID card covers for my 2-year old's music player so he can hear his audio books. 

All of the covers (it's about 140) are easily available at Amazon (DE, search for eg "Benjamin Bluemchen mc 109") but when I use SACAD, it always downloads the square CD cover...

Is there any way to get the 800 x 1200 covers instead? Or is this an issue with the search term? I assume SACAD uses the same search engine at Amazon as the manual search. 

I would be greatful for an help!

**Comment by desbma** [comment]
Sacad explicitly favors square covers, because it is designed to look for CD covers, and this allows filtering out many unwanted images.

Sorry I do not intend to change this.
