### ISSUE TITLE
non issue, user contributed wrapper script

### ISSUE THREAD

**Issue by cirrusUK** [desbma/sacad#35]
```
#!/usr/bin/env bash
tput setaf 5
read -p "enter name of artist album art:" artist
tput setaf 1
read -p "enter name of the album requiring art:" album
tput setaf 6
~/venv/bin/sacad -v normal "${artist}" "${album}" 150  ~/"${album}.jpg"
tput setaf 2
echo -n " yay ! "${album}.jpg" album art will be in your home directory."
```

#TODO integrate [fancy_audio](https://github.com/ajitsing/fancy_audio) to auto embed downloaded art.
[http://ix.io/2eE3/](url)

**Comment by desbma** [comment]
`sacad_r` can already embed covers if you need that.

I'm closing this since this is not an issue. 
If you want to discuss integrating several programs in personal scripts, maybe sites like the Arch forums are a better place.
