### ISSUE TITLE
sacad_r: multithreading

### ISSUE THREAD

**Issue by maszaa** [desbma/sacad#36]
The search would be lot more faster if sacad_r would use multiple threads. Let's say by default the amount of CPU cores.

**Comment by desbma** [comment]
It already uses asyncio, which is much faster than threads and allows many more parallel work that you have CPU cores.

**Comment by maszaa** [comment]
I know it uses asyncio. But why I only see one sacad_r process eating 100% of one core all the time?

**Comment by maszaa** [comment]
To continue, the program would run a lot faster if it could utilize 100% of all available cores.

**Comment by desbma** [comment]
The execution time is not limited by your CPU's speed, it's limited by the response time of the various servers.
The only CPU intensive task is the PNG crunching, and if you had 10 running at the same time, it would use 10 cores at 100%.
