### ISSUE TITLE
Maintain the original format of the found image?

### ISSUE THREAD

**Issue by vicmarto** [desbma/sacad#37]
Suggestion: Would be possible to add a option to maintain the original format of the found image? (ie. save a png if the found image is a png. Save a jpg if the found image).

Thanks, good program.

**Comment by desbma** [comment]
Seems like a good idea.

**Comment by desbma** [comment]
Implemented by https://github.com/desbma/sacad/commit/c102875550fa3af8bc4d27db343b12b00934fabb.

**Comment by vicmarto** [comment]
Thank you very much!   : )
