### ISSUE TITLE
Search cover with wildcar or regex

### ISSUE THREAD

**Issue by maszaa** [desbma/sacad#38]
Would be nice, if the program would allow folders to have images with different patterns, e.g. Folder.*, *.jpg or even a search with a regex.

**Comment by desbma** [comment]
See https://github.com/desbma/sacad/issues/32#issuecomment-597027277
> Sacad only supports library which are tagged and organized with consistent conventions, and I do not intend to change this.

> However with a bit of scripting I should be possible for you to rename all images to have a similar name, remove all embedded overs (or embed them all), etc.

It's best to invest time to organize your library neatly, than to make other tools work around that by trying guess its content or layout.

**Comment by maszaa** [comment]
Well, how are you going to implement this if the image name is hardcoded to include the format? https://github.com/desbma/sacad/issues/37
