### ISSUE TITLE
Discussion: Support ASIN for Unambiguous Query

### ISSUE THREAD

**Issue by baoshan** [desbma/sacad#4]
Amazon's search feature support ASIN (you can enter `B004TUDEAU` for example). This is a good candidate for unambiguous query: a lot of re-releases have the same album title as the original one.

Currently, feed `ASIN` to `sacad` command line will lead to non-match from `AmazonCD` or `AmazonDigitalMusic`. Can this be improved?

Thanks.

**Comment by desbma** [comment]
Sorry, I do not intend to support this.

This is Amazon specific, and break the 'search by artist/album' paradigm (which for example, is what allows searching automatically from audio tags).
