### ISSUE TITLE
sacad_win64.exe release 2.3.0 seems to be broken

### ISSUE THREAD

**Issue by StevenMeadowbrook** [desbma/sacad#44]
Fellow sacad heroes.
First of all many thanks for your work.
Unfortunately after downloading the new version the application crashes after invocation with the hint on a missing resource.
Possibly something is missing.
2.2.3 works rather fine.

**Comment by desbma** [comment]
Hi,

Can you post more information about what error is thrown ?

**Comment by nnpcYvIVl** [comment]
@desbma 

Same problem. I am using sacad_win64.exe. 2.2.3 works fine. See attached stacktrace.

```
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Python36\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
  File "sacad\recurse.py", line 15, in <module>
ModuleNotFoundError: No module named 'resource'
```

**Comment by desbma** [comment]
Should be fixed by https://github.com/desbma/sacad/commit/ded7ccce0bbe6096535c7be004f31e3727887c7e
Version 2.3.1 coming soon
