### ISSUE TITLE
FakeUserAgentError and SSL Certificate Problems

### ISSUE THREAD

**Issue by tadzik-chrust** [desbma/sacad#46]
I'm on OSX 10.14.5, python versions 2.7.10 and 3.8.5. In terminal, I tried using sacad_r on a tree of folders and on a single album folder using sacad_r LOCATION 600 Folder.jpg and each time I am getting this readout. I'm a newbie and desperately need help with this. What is the issue here and how can I fix it? Thank you.

> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1350, in do_open
>     h.request(req.get_method(), req.selector, req.data, headers,
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1255, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1301, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1250, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1010, in _send_output
>     self.send(msg)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 950, in send
>     self.connect()
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1424, in connect
>     self.sock = self._context.wrap_socket(self.sock,
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
>     return self.sslsocket_class._create(
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
>     self.do_handshake()
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fake_useragent/utils.py", line 64, in get
>     with contextlib.closing(urlopen(
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 525, in open
>     response = self._open(req, data)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 542, in _open
>     result = self._call_chain(self.handle_open, protocol, protocol +
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
>     result = func(*args)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1393, in https_open
>     return self.do_open(http.client.HTTPSConnection, req,
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1353, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fake_useragent/utils.py", line 154, in load
>     for item in get_browsers(verify_ssl=verify_ssl):
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fake_useragent/utils.py", line 97, in get_browsers
>     html = get(settings.BROWSERS_STATS_PAGE, verify_ssl=verify_ssl)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fake_useragent/utils.py", line 84, in get
>     raise FakeUserAgentError('Maximum amount of retries reached')
> fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1350, in do_open
>     h.request(req.get_method(), req.selector, req.data, headers,
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1255, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1301, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1250, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1010, in _send_output
>     self.send(msg)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 950, in send
>     self.connect()
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1424, in connect
>     self.sock = self._context.wrap_socket(self.sock,
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
>     return self.sslsocket_class._create(
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
>     self.do_handshake()
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fake_useragent/utils.py", line 64, in get
>     with contextlib.closing(urlopen(
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 525, in open
>     response = self._open(req, data)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 542, in _open
>     result = self._call_chain(self.handle_open, protocol, protocol +
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
>     result = func(*args)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1393, in https_open
>     return self.do_open(http.client.HTTPSConnection, req,
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1353, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.8/bin/sacad_r", line 11, in <module>
>     load_entry_point('sacad==2.3.2', 'console_scripts', 'sacad_r')()
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sacad/recurse.py", line 447, in cl_main
>     get_covers(work, args)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sacad/recurse.py", line 362, in get_covers
>     asyncio.get_event_loop().run_until_complete(root_future)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
>     return future.result()
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sacad/recurse.py", line 297, in post_download
>     status = future.result()
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sacad/__init__.py", line 25, in search_and_download
>     cover_sources = [sources.LastFmCoverSource(*source_args),
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sacad/sources/lastfm.py", line 34, in __init__
>     super().__init__(*args, min_delay_between_accesses=0.1, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sacad/sources/base.py", line 43, in __init__
>     self.ua = fake_useragent.UserAgent(path=os.path.join(ua_cache_dir, "ua.json"))
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fake_useragent/fake.py", line 69, in __init__
>     self.load()
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fake_useragent/fake.py", line 75, in load
>     self.data = load_cached(
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fake_useragent/utils.py", line 250, in load_cached
>     update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fake_useragent/utils.py", line 245, in update
>     write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fake_useragent/utils.py", line 187, in load
>     ret = json.loads(get(
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fake_useragent/utils.py", line 84, in get
>     raise FakeUserAgentError('Maximum amount of retries reached')
> fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

**Comment by desbma** [comment]
Try updating your certificates with `pip3 install -U certifi`.

**Comment by bonelifer** [comment]
That should be this as -u isn't a recognized parameter(so sayeth pip3):
pip3 install --upgrade certifi

**Comment by desbma** [comment]
`-U` not `-u`
