### ISSUE TITLE
More picky config ? -- but especially THANK YOU !

### ISSUE THREAD

**Issue by tintamarre** [desbma/sacad#49]
First, congratulations on your great job. 👍 I really like to download every covers of my music folder at once. Super useful. 🥇 

Issue
----

When downloading covers for my entire library, `sacad_r` download sometimes the wrong cover (especially from less known artists). Would it be possible to set it up to be more picky ?

**Comment by desbma** [comment]
The code already tries to avoid unrelated covers when sorting results to choose the one to download, by considering source reliability and visually comparing image with a reference if we found one. You also have the `-d` / `--disable-low-quality-sources` option but that currently only disables the Google source, which is broken and does not return any result anyway.

I you can find a query where the wrong result is chosen **and** a better result is available I can look at it, but for difficult queries (rare albums or ambiguous words), wrong results will unavoidably be more likely to appear.
