### ISSUE TITLE
Last.fm regularly 400 error (possibly) due to shared API_Key? 

### ISSUE THREAD

**Issue by baoshan** [desbma/sacad#5]
I received below error regularly:

`Search with source 'LastFmCoverSource' failed: HTTPError 400 Client Error: Bad Request for url: https://ws.audioscrobbler.com/2.0/?method=album.getinfo&api_key=2410a53db5c7490d0f50c100a020f359&`

Can this be mitigated through a mechanism to use my own `last.fm` developer api key?

Thanks.

**Comment by desbma** [comment]
It's unusual for a REST API, but Last.fm actually returns a HTTP 400 error when a query returns no results.

So unless you get that error for **every** query, there is nothing to worry about, it just means "no results".

**Comment by baoshan** [comment]
Thanks for the explanation! What's the difference between a ` 0 relevant (0 excluded) ` and the `400 Error`?

If that's expected behavior (from `sacad`'s side), can the `lastfmsource` catch the `400` error and treat it as an empty result?

Thanks.

**Comment by desbma** [comment]
> What's the difference between a ` 0 relevant (0 excluded) ` and the `400 Error`?

The first is the standard output when a source has no results, the second is the error Last.fm returns when it has no results. The 400 error code is returned by the Last.fm server, so this is not in my control.

> If that's expected behavior (from sacad's side), can the lastfmsource catch the 400 error and treat it as an empty result?

I could do that, but in the code that would break the clean separation between source specific logic and generic HTTP handling (which is the same for all sources). And that would provide little benefit.

**Comment by baoshan** [comment]
Thanks, but why the `lastfm` source returns `0 relevant (0 excluded)` for some query and `400 Error` for others? Works fine, just curiosity. :P

<img width="928" alt="screen shot 2016-02-17 at 9 54 06 am" src="https://cloud.githubusercontent.com/assets/1096182/13097507/9479a3b2-d55c-11e5-88cc-f418a362a269.png">
<img width="561" alt="screen shot 2016-02-17 at 9 54 36 am" src="https://cloud.githubusercontent.com/assets/1096182/13097508/94e322ec-d55c-11e5-9d00-0bb7a1d32eb0.png">

Cache is emptied when executing above commands.

**Comment by desbma** [comment]
[AB CD](http://www.last.fm/music/AB/CD) is actually an artist so a query for that on Last.fm does not return an error.

**Comment by baoshan** [comment]
If the `lastfm` API is designed as returns a `404`, will `sacad` catch that?

**Comment by desbma** [comment]
Not sure I understand your last question, but all HTTP or TCP errors should print the `Search with source 'XXX' failed: YYY` line.

**Comment by baoshan** [comment]
Sorry, I'll explain.

`404` should not be used to represent an empty set (best practice). But that's definitely better than `400`. If `last.fm` api use `404` for no result matched. Will the `lastfm` source log the error?

I'm just pushing you to catch the known `lastfm` design issue. Each source has its own specific issues to face. We're talking about the micro-architecting here.

If we document the interface between `source` and `sacad`. It'll not be on HTTP level. the `400` definitely means `empty set` here, and a regular `[]` should be passed between `source` and `sacad`.
