### ISSUE TITLE
Back cover support?

### ISSUE THREAD

**Issue by isenmann** [desbma/sacad#50]
Hi, thanks for this very good tool. I'm planning to use your tool in my current little project which will be available on GitHub as soon as a first usable version is ready. 

Is there any possibility to have back cover support into sacad? I have seen in the google source that "front cover" is explicit set, couldn't find any similar in the other sources. 

Thanks,
Daniel

**Comment by desbma** [comment]
Sorry I don't intend to add support for back covers.

Some sources may have back covers, most probably won't. Feel free to hack the code or fork the project if you need that.
