### ISSUE TITLE
Question: How to overwrite all Albumarts of all files in a directory ?

### ISSUE THREAD

**Issue by stulluk** [desbma/sacad#52]
I am using v2.3.4.

I have bunch of mp3 files, categorised as directories with Artist Names. Some of those mp3 files have Albumarts, some do not, and some have wrong albumarts.

Something like:
- Music_Top_Dir
    - Artist-1
        - Song-1.mp3
        - Song-2.mp3 
    - Artist-2
        - Song-X.mp3
        - Song-Y.mp3

Is there a way to overwrite all albumarts of all mp3 files in a directory ? 

Note: When I run sacad_r in a sample artist directory, I get:

`stulluk ~/Desktop/GULSEN $  sacad_r . 500 +
Analyzing library: 1dir [00:00, 44.52dir/s, files=21, albums=1, missing covers=1, errors=0]
sacad_r: Error occured while embedding cover for 'Bir İhtimal Biliyorum' by 'Gülşen' from './Be.Adam.mp3', './Bir.ihtimal.biliyorum.mp3', './Canin.Sagolsun.mp3', './Delikanlim.mp3', './Dillere.Dusecegiz.Seninle.mp3', './Ezberbozan.mp3', './Gel.Carem.mp3', './Iltimas.mp3', './Irgalamaz.Beni.mp3', './Kardan.Adam.mp3', './Nazar.Degmesin.mp3', './Ne.Kavgam.Bitti.Ne.Sevdam.mp3', './Nirvana.mp3', './Of.Of.mp3', './Onsoz.mp3', './Sakincali.mp3', './Sarisinim.mp3', './Saz.mi.Caz.mi.mp3', './Ya.tutarsa.mp3', './Yurtta.Ask.Cihanda.Ask.mp3': AttributeError 'NoneType' object has no attribute 'add'
Searching covers: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.08cover/s, ok=0, errors=1, no result found=0]
stulluk ~/Desktop/GULSEN $ `

**Comment by desbma** [comment]
You need to pass `-i` flag:
```
  -i, --ignore-existing
                        Ignore existing covers and force search and download for all files (default: False)
```

 > AttributeError 'NoneType' object has no attribute 'add' 

This issue is similar to #51 and has already been fixed, but this fix is not yet in a release. You can install from source if you want the fix right now. However this error occurs for MP3 files having no tags, and at least one of the files for an album needs to have tags, otherwise Sacad has nothing to search for.

**Comment by stulluk** [comment]
I installed latest v2.3.4 from git (master branch) and below is the result. Where am I doing a mistake?

stulluk ~/Desktop/SEBNEM.FERAH $  ls 
Babam-Oglum.mp3            Bu-Ask-Fazla-Sana.mp3  Cakil-Taslari.mp3  Deli-Kizim-Uyan.mp3  Gozlerimin-Etrafindaki-Cizgiler.mp3  Hoscakal.mp3       Od.mp3       Oyunlar.mp3  Sil-Bastan.mp3          Yagmurlar.mp3      Yalniz.mp3
Ben-Sarkimi-Soylerken.mp3  Bugun.mp3              Can-Kiriklari.mp3  Firtina.mp3          Her-Sey-Insanlar-Icin.mp3            Mayin-Tarlasi.mp3  Okyanus.mp3  Sigara.mp3   Vazgectim-Dunyadan.mp3  Ya-Hep-Ya-Hic.mp3
stulluk ~/Desktop/SEBNEM.FERAH $  sacad_r -i . 500 + 
sacad_r: Unable to read metadata for album directory '.'                              
Analyzing library: 1dir [00:00, 25.80dir/s, files=21, albums=0, missing covers=0, errors=1]
Searching covers: 0cover [00:00, ?cover/s, errors=0, no result found=0, ok=0]
stulluk ~/Desktop/SEBNEM.FERAH $  sacad -h
usage: sacad [-h] [-t SIZE_TOLERANCE_PRCT]
             [-a {ca,cn,fr,de,co.jp,co.uk} [{ca,cn,fr,de,co.jp,co.uk} ...]]
             [-d] [-p] [-v {quiet,warning,normal,debug}]
             artist album size out_filepath

SACAD v2.3.4. Search and download an album cover.

positional arguments:
  artist                Artist to search for
  album                 Album to search for
  size                  Target image size
  out_filepath          Output image filepath

optional arguments:
  -h, --help            show this help message and exit
  -t SIZE_TOLERANCE_PRCT, --size-tolerance SIZE_TOLERANCE_PRCT
                        Tolerate this percentage of size difference with the
                        target size. Note that covers with size above or close
                        to the target size will still be preferred if
                        available (default: 25)
  -a {ca,cn,fr,de,co.jp,co.uk} [{ca,cn,fr,de,co.jp,co.uk} ...], --amazon-sites {ca,cn,fr,de,co.jp,co.uk} [{ca,cn,fr,de,co.jp,co.uk} ...]
                        Amazon site TLDs to use as search source, in addition
                        to amazon.com (default: ())
  -d, --disable-low-quality-sources
                        Disable cover sources that may return unreliable
                        results (ie. Google Images). It will speed up search
                        and improve reliability, but may fail to find results
                        for some difficult searches. (default: False)
  -p, --preserve-format
                        Preserve source image format if possible. Target
                        format will still be prefered when sorting results.
                        (default: False)
  -v {quiet,warning,normal,debug}, --verbosity {quiet,warning,normal,debug}
                        Level of logging output (default: normal)
stulluk ~/Desktop/SEBNEM.FERAH $

**Comment by desbma** [comment]
You files are missing tags.

Sacad can not know what to search for if your files do not have artist and album tags.
