### ISSUE TITLE
feature request: support downloading cover art for entire artist discography

### ISSUE THREAD

**Issue by 07416** [desbma/sacad#54]
Would be highly useful for productive artists such as [Zappa](https://en.wikipedia.org/wiki/Frank_Zappa_discography) — I don't have all of the music I listed stored locally and viewing high-quality artwork remains a challenge.

A decent way would be supporting artist pages on Deezer (such as `https://www.deezer.com/en/artist/1`) to avoid large numbers of unrelated results.

**Comment by desbma** [comment]
I understand your need, but this is out of the scope of this tool.
Sacad is only for downloading front album covers.

**Comment by 07416** [comment]
> Sacad is only for downloading front album covers.

This is what I mean, if you misunderstood. The request is about downloading the (front) covers for entire artist album catalogue.

**Comment by desbma** [comment]
By front cover I mean the actual album front cover, not an artist image that you want to set a front cover.

**Comment by desbma** [comment]
Sorry I don't understand your request then. You want the ability to download front covers for all the albums of an artist, without querying each album?

**Comment by 07416** [comment]
> You want the ability to download front covers for all the albums of an artist, without querying each album?

Yes!
