### ISSUE TITLE
[feature request] Search by cover source

### ISSUE THREAD

**Issue by 07416** [desbma/sacad#55]
Google and Amazon domains are blocked in my network, and I prefer Deezer since they appear to have quite high-res album artwork.

**Comment by desbma** [comment]
Sorry this is not currently supported.

Amazon currently has the highest resolution covers (up to 2560px), but that depends on the query of course.

**Comment by 07416** [comment]
> Sorry this is not currently supported.

Rebranded as feature request. Hopefully trivial to implement.

**Comment by maszaa** [comment]
Cover source selection would also implement https://github.com/desbma/sacad/issues/53

**Comment by desbma** [comment]
Implemented via https://github.com/desbma/sacad/commit/10af84f6bd55c0b873a72c3d2c39236d912c9c8c
