### ISSUE TITLE
can we use?

### ISSUE THREAD

**Issue by roydekleijn** [desbma/sacad#58]
Hi,

Awesome tool!, but my question is.. Are we allowed to use those images freely?
Or are there restrictions of some sort?

**Comment by desbma** [comment]
The images belong to the artist or record company that owns the album rights I suppose.
I am not a lawyer and I don't know if they are restrictions on their use, in which country, etc.
For private use, this is probably safe.

**Comment by roydekleijn** [comment]
I want to use them for a test/demo application I created which will be used for teaching people software testing.

**Comment by desbma** [comment]
Sacad is a tool that search for covers on different public sources (Amazon, Last.fm...).
You have to check on theses sources, or for each cover, what you are allowed to do or not with the images.
Sorry I can't provide a general answer.
