### ISSUE TITLE
Failed to compile 

### ISSUE THREAD

**Issue by SinisterSoup1** [desbma/sacad#59]
When i attempt to compile i get the error message:

error: Setup script exited with error: command 'x86_64-unknown-linux-gnu-gcc' failed: No such file or directory

im using Void linux with gnome 4.0

**Comment by desbma** [comment]
This is a pure Python package, so I suppose you have an error when compiling one of the dependencies?
I'm not familiar with Void Linux, bur from a quick Google search I think you need to install the `python3-devel` package.
Installing `python3-lxml` could also probably prevent any compilation from being needed.

**Comment by SinisterSoup1** [comment]
That worked! thanks for the help
