### ISSUE TITLE
sacad: error: argument size: invalid int value: 'cover.jpg'

### ISSUE THREAD

**Issue by Stooovie** [desbma/sacad#64]
Any filename for the output image gives me this error: 

sacad: error: argument size: invalid int value: 'cover.jpg' 

This is the example command: sacad /Volumes/Public/iTunes\ Media/Music/Abba 640 cover.jpg

Any clues? MacOS 11.6, sacad installed today, so, up-to-date. Thanks.

**Comment by desbma** [comment]
You probably want to run `sacad_r` instead of `sacad`.

`sacad` searches for a single cover. `sacad_r` recursively searches for each album cover in a directory tree.

See `sacad -h` /  `sacad_r -h` for help for each command.
