### ISSUE TITLE
Resizing Doesn't Always Work

### ISSUE THREAD

**Issue by lazerfloyd** [desbma/sacad#69]
For context, the source image downloaded from the web is 1000x1000 pixels.

Typing the following:
`sacad -v normal -s deezer googleimageswebscrape lastfm -p 'The Beatles' 'Rubber Soul' 800 test.png`

Sacad downloads the image from Deezer and saves it as 1000x1000px without resizing. This happens with every numerical value I've tested from 800 up to 1000. Any value less than 800, starting from 799, resizes the image properly. This happens whether the output format is PNG or JPEG.

**Comment by desbma** [comment]
Use `-t 0` if you want to get the exact target size.

```
$ sacad -h
...
  -t SIZE_TOLERANCE_PRCT, --size-tolerance SIZE_TOLERANCE_PRCT
                        Tolerate this percentage of size difference with the target size. Note that covers with size above or close to the target size will still be preferred if available
                        (default: 25)
...
```
