### ISSUE TITLE
Sacad_r produces zero results.

### ISSUE THREAD

**Issue by Miusaky** [desbma/sacad#71]
Hello,

Running `sacad_r -f -i $dir 800 "+"` produces no results. 

```
Analyzing library: 1dir [00:00, 30.44dir/s, files=60, albums=52, missing covers=52, errors=0]
Searching covers: 100%|██████████████████████████████████████████████████████████████████████████| 52/52 [00:14<00:00,  3.55cover/s, ok=52, errors=0, no result found=0]
```

My collection is not divided into artist/album folders. Current structure is Music > Genre > Songs however full metadata should be embedded and songs are named `ARTIST - SONGNAME`

I had assumed the -f flag was intended to be used for structures like mine however since it finds 0 results I'm wondering if that is perhaps not the case? 

The music I've tested it with is mainstream and exists on deezer and other services' servers.

**Comment by Miusaky** [comment]
> What makes you think it "produces no result"? 

`no result found=0`

This bit + kunst not showing the art (but that is perhaps a different issue). Any Linux tool to view embedded metadata/art?

**Comment by desbma** [comment]
Maybe I should reword that if you find it confusing but `no result found=0` means the count of searches for which no results were found is 0.

> Any Linux tool to view embedded metadata/art?

Try mpv or easytag.

**Comment by Miusaky** [comment]
Thanks!
