### ISSUE TITLE
how to exclude one source or specify some sources?

### ISSUE THREAD

**Issue by wbtcpip2** [desbma/sacad#75]
in the win32 version is it possible to exclude one source? (i don't want to use amazondigital because it returns a lot of false results) 
or is it possible to specify that i only want to use discogs and amazoncd? it seems the -s option only accept one value?

**Comment by desbma** [comment]
You need to pass space separated source names, ie: `-s discogs amazoncd`

**Comment by wbtcpip2** [comment]
thank you

**Comment by wbtcpip2** [comment]
when i try:
sacad -s discogs amazoncd "STEREO MC'S" "WE BELONG IN THIS WORLD 2GHETE" 320 pippo.jpg

i get

sacad: error: argument -s/--cover-sources: invalid choice: "STEREO MC'S" (choose from 'amazoncd', 'amazondigital', 'deezer', 'discogs', 'googleimageswebscrape', 'lastfm')

**Comment by desbma** [comment]
Try: `sacad "STEREO MC'S" "WE BELONG IN THIS WORLD 2GHETE" 320 /tmp/pippo.jpg -s discogs amazoncd`

**Comment by wbtcpip2** [comment]
working now thank you

**Comment by gingerbeardman** [comment]
It's puzzling that the parameters need to be put at the end, this is not clear from the `-h` option

**Comment by desbma** [comment]
It's a known limitation of Python's argparse module.

Another alternative is to use `--` to separate optional arguments from positional arguments, see https://docs.python.org/3/howto/argparse.html#specifying-ambiguous-arguments 
So for example : `sacad -s discogs amazoncd -- "STEREO MC'S" "WE BELONG IN THIS WORLD 2GHETE" 320 pippo.jpg`

**Comment by gingerbeardman** [comment]
it should be mentioned in -h
