### ISSUE TITLE
Feature request: Apple Music's artwork

### ISSUE THREAD

**Issue by wbtcpip2** [desbma/sacad#76]
i saw this Python package that download covers from Apple Music

https://pypi.org/project/get-cover-art/

would it be possible in the future to add Apple Music as a source on sacad?

thank you

**Comment by desbma** [comment]
Done https://github.com/desbma/sacad/commit/d7530fc28358fe9341984c13545f937f38058bc9

**Comment by gingerbeardman** [comment]
FWIW, iTunes and Apple Music are different.

- https://bendodson.com/projects/apple-music-artwork-finder/
- https://bendodson.com/projects/itunes-artwork-finder/

**Comment by gingerbeardman** [comment]
@desbma do you want to reopen #76? it was a for Apple Music (but you added iTunes)

**Comment by desbma** [comment]
No, open a new issue. The reporter in #76 was referring to a project that uses [itunes.apple.com](https://github.com/regosen/get_cover_art/blob/552a1607f15ec9ad058c50819b807c22c472299a/get_cover_art/apple_downloader.py#L10)
