### ISSUE TITLE
Question about one cover

### ISSUE THREAD

**Issue by wbtcpip2** [desbma/sacad#77]
Hi
`sacad.exe "Ricky Rivaro ft. Tiger Lilly" "With You" 320 "D:\Pictures\Ricky Rivaro ft. Tiger Lilly - With You.jpg" -t 100 -s discogs amazoncd itunes deezer`
did not found any cover
but here i see the cover in discogs: https://www.discogs.com/release/1060453-Ricky-Rivaro-Feat-Tiger-Lilly-With-You

am i doing something wrong?

**Comment by desbma** [comment]
"Ricky Rivaro ft. Tiger Lilly" is not an artist, "Ricky Rivaro" however is, and sacad gets the above cover if you pass that as artist.
