### ISSUE TITLE
Windows problem

### ISSUE THREAD

**Issue by parsonsm99** [desbma/sacad#81]
Hi when using the Windows version - any help appreciated.
Thanks,
mike.

C:\Users\Mike\Home-PC-D-Drive\Mike\Perl\sacad-win64>sacad.exe "Andy Black" "The Shadow Side" 256 art.jpg
Main: jpegoptim could not be found, JPEG crunching will be disabled
Main: optipng could not be found, PNG crunching will be disabled
DeezerCoverSource: Got 3 relevant (2 excluded) results from source 'DeezerCoverSource'
DiscogsCoverSource: Got 6 relevant (0 excluded) results from source 'DiscogsCoverSource'
LastFmCoverSource: Got 2 relevant (3 excluded) results from source 'LastFmCoverSource'
AmazonCdCoverSource: Got 1 relevant (0 excluded) results from source 'AmazonCdCoverSource'
AmazonDigitalCoverSource: Got 14 relevant (0 excluded) results from source 'AmazonDigitalCoverSource'
ItunesCoverSource: Got 1 relevant (0 excluded) results from source 'ItunesCoverSource'
Cover: Removed 13 duplicate results
Cover: Reference is: LastFmCoverSourceResult 'https://lastfm.freetls.fastly.net/i/u/300x300/93ff0dd2226805dea5afa0c7f876e986.jpg'
Cover: Downloading cover 'https://i.discogs.com/GpeEbYD_3GOVAiwHUub4Wat_SSD9ugDTxybWe_PoTzE/rs:fit/g:sm/q:90/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTg0NzQy/NjQtMTQ2MjMwNzkw/Mi0xNTEzLmpwZWc.jpeg' (part 1/1)...
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F24ADB05E0>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 719, in call_soon
  File "asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F24ADB05E0>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 719, in call_soon
  File "asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F24ADB05E0>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 719, in call_soon
  File "asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
...

**Comment by desbma** [comment]
Despite the error logs, is the cover properly downloaded to `art.jpg`?

**Comment by parsonsm99** [comment]
Hi, no. Nothing downloaded.
Mike.

**Comment by desbma** [comment]
Are you sure ? I don't see any error in your logs that could explain the file not being downloaded, the errors occur when the program is closing and should have not effect apart from the log spam annoyance.
I can reproduce the exact same output, but the  `art.jpg` file is downloaded just fine.

**Comment by parsonsm99** [comment]
Sorry! It now works OK.
I don't get all the messages and it downloads fine.
Thanks,
Mike.
