### ISSUE TITLE
TypeError--init--()

### ISSUE THREAD

**Issue by CrazyWolf13** [desbma/sacad#83]
![image](https://user-images.githubusercontent.com/96661824/204034607-1f29da1d-27e9-4d3d-9914-072069a97405.png)

What am i doing wrong?
Or is this a Bug?

**Comment by CrazyWolf13** [comment]
@desbma

**Comment by desbma** [comment]
Duplicate of #82

**Comment by CrazyWolf13** [comment]
> 

I downloaded the latest release 4 hours ago so its not fixed :/

**Comment by desbma** [comment]
I released the fix less than 2 hours ago.
