### ISSUE TITLE
improvement proposal and clarification

### ISSUE THREAD

**Issue by chicco64** [desbma/sacad#84]
Hi !
I ask you if it is possible;
1) reduce the search only on a single music database (eg lastfm) excluding the others; how the search execution file should be written with this parameter;
2) insert a "fixed" image (which could be the logo of the radio station) to be recalled automatically when sacad can't find the exact cover of the selected song; this to avoid the publication of images that are not consistent with the song;
Many thanks for your reply, your software is really helpful in many occasions.

**Comment by desbma** [comment]
Hi,

1. `sacad <artist> <album> <size> <path> -s lastfm` or `sacad -s lastfm -- <artist> <album> <size> <path>`

2. You can do that with a simple script that runs sacad and copies an image file if sacad did not find any result
