### ISSUE TITLE
improvement proposal: prioritize CD or digital covers over vinyl

### ISSUE THREAD

**Issue by wbtcpip2** [desbma/sacad#85]
when i call

sacad-win32\sacad.exe "michael jackson" "black or white" 320 "Michael Jackson - Black or White.jpg" -t 1000 -s discogs

i get an ugly vinyl cover

https://i.discogs.com/wllaWMd5jPBEpXQK3oaLxy3Pz32qptU-8Ueh1IUGCpQ/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE4Mjk1/MDA5LTE2MTg0MTc0/NDctOTkyNC5qcGVn.jpeg

 instead of this: https://www.discogs.com/it/release/635588-Michael-Jackson-Black-Or-White

it would be nice to search first for cd covers and if nothing found search for the rest

**Comment by desbma** [comment]
Fixed in e728c9b97e706b45a644745f0cc1277ca1e8f8b6

**Comment by wbtcpip2** [comment]
thank you
