### ISSUE TITLE
should use mutagen add_picture() for FLAC files

### ISSUE THREAD

**Issue by spedrickson** [desbma/sacad#86]
Not sure if this is a bug, so much as an issue of maximum compatibility. 

As mentioned at the _very_ bottom of this mutagen guide, FLAC supports images directly: https://mutagen.readthedocs.io/en/latest/user/vcomment.html#embedded-images

Currently for FLAC files, sacad will embed the images inside a vorbis comment named `metadata_block_picture` , which is supported in some programs (mpv, vlc), but is not as widely supported as the `METADATA_BLOCK_PICTURE` block [defined by the FLAC spec](https://xiph.org/flac/format.html#metadata_block_picture). 

For example, the official [`metaflac` program ](https://xiph.org/flac/documentation_tools_metaflac.html)returns an error if you try to export the picture using the built-in function:
```bash
metaflac ./current_method.flac --export-picture-to ./test.jpg
current_method.flac: ERROR: FLAC file has no PICTURE block
```

But if you replace lines 257/258:
https://github.com/desbma/sacad/blob/ccc16f2bade9530c75906083b0f69ba131a206ba/sacad/recurse.py#L255-L259

With:
```python3
if filepath.endswith('.flac'):
    mf.add_picture(picture)
else:
    encoded_data = base64.b64encode(picture.write())
    mf["metadata_block_picture"] = encoded_data.decode("ascii")
```

`metaflac` can now export the picture properly. It also makes artwork show up properly in foobar2000, where before it wasn't detected at all for me.

Not sure if album art detection would also need to be fixed to check the [list of pictures](https://mutagen.readthedocs.io/en/latest/api/flac.html#mutagen.flac.FLAC.pictures) if this change is implemented.

**Comment by desbma** [comment]
Thanks for the precise report, can you test c48cc07d7dd935339cc57c84e1546bcaa27c2a37?

**Comment by spedrickson** [comment]
Working for me, it added pictures to FLAC files in a way recognizable by metaflac and foobar2000.

Also correctly skipped files that had artwork in header blocks from other tools, which it looks like was also changed.

Thanks!
