### ISSUE TITLE
All searches fail because I pre-pend the Album title in the ID3 tag with "(Release Year)"

### ISSUE THREAD

**Issue by SliderJeff** [desbma/sacad#88]
Is there a way to tell sacad_r to ignore a portion of the title when sending the search string?  It seems like it's looking for exact matches on the various album art sites and this is causing it to return 0 matches.  Thanks.

**Comment by desbma** [comment]
Short answer: 
No there is no way to alter the artist value extracted from the tags before the search is done by `sacad_r`.

Long answer: 
For some tag formats you can use 2 different album values, for example "album" for players with a value prepended, and "_album" with the real value that `sacad_r` will use if if it present. But ID3 only has a single possible tag for the album, so it would not work for this format.
Other possibility: don't use `sacad_r`, but write a script that extracts the tag values, removes the year, and runs `sacad` with the real album value.

**Comment by SliderJeff** [comment]
Ok, thanks for the quick response!
