### ISSUE TITLE
Search with source AmazonCdCoverSource failed

### ISSUE THREAD

**Issue by wbtcpip2** [desbma/sacad#89]
sacad-win32\sacad.exe "Michale Jackson" "Thriller" 160 "e:\Michael Jackson - thriller.jpg" -t 1000 -s amazoncd

Main: jpegoptim could not be found, JPEG crunching will be disabled
Main: optipng could not be found, PNG crunching will be disabled
AmazonCdCoverSource: Search with source 'AmazonCdCoverSource' failed: ClientResponseError 503, message='Service Unavailable', url=URL('https://www.amazon.com/s?i=popular&rh=p_32:michale+jackson,p_28:thriller&s=relevancerank')
Cover: No reference result found
Main: No results

is it possible to fix the AmazonCdCoverSource?

**Comment by desbma** [comment]
It should be "fixed", or rather worked around because we are at the mercy of Amazon if they decide to block our queries.
