### ISSUE TITLE
Progressive JPEG

### ISSUE THREAD

**Issue by edelstahlratte** [desbma/sacad#90]
Hello,

is it possible to avoid progressive JPEG images or re-save them on the fly as non-progressive files?

Thank you,

Nico.

**Comment by desbma** [comment]
Hi, 

Do you have an example of sacad invocation that leads to downloading a progressive JPEG ?

**Comment by edelstahlratte** [comment]
Hello 

and thanks for your response...

this gives me a progressive JPEG:

`sacad "Meat Beat Manifesto" "Subliminal Sandwich" 600 AlbumArt.jpg`

**Comment by desbma** [comment]
What is the URL that is downloaded when you run that command ?

When I run it here, the resulting image file does not seem to be progressive JPEG.

**Comment by edelstahlratte** [comment]
`Cover: Downloading cover 'https://i.discogs.com/PmIViK7oa7birbtqlJUnBezsLz7lYBwcQKxM7Efk52w/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMxODkt/MTE3MTQzMzgxNy5q/cGVn.jpeg' (part 1/1)...`

Image info shows progressive JPEG...

![Bildschirmfoto](https://github.com/desbma/sacad/assets/17500289/3e796631-bdfe-4eb9-8875-787566a58c40)

**Comment by desbma** [comment]
I have to disagree with the tool you are using.

I tried several different tools (namely: [file](https://www.darwinsys.com/file/), [exiftool](https://exiftool.org/), [GraphicsMagick](http://www.graphicsmagick.org/), [ImageMagick](https://imagemagick.org/index.php)), and [other methods](https://superuser.com/questions/1010734/how-can-i-tell-if-a-jpeg-was-saved-as-progressive), and all indicate that this file is NOT progressive.

**Comment by edelstahlratte** [comment]
Hello,

now it's time for me to disagree :)

Here is my exiftool output:

```
ExifTool Version Number         : 12.40
File Name                       : AlbumArt2.jpg
Directory                       : .
File Size                       : 177 KiB
File Modification Date/Time     : 2023:06:27 14:20:01+02:00
File Access Date/Time           : 2023:07:04 19:21:58+02:00
File Inode Change Date/Time     : 2023:06:27 14:20:01+02:00
File Permissions                : -rw-rw-r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Exif Byte Order                 : Little-endian (Intel, II)
Orientation                     : Horizontal (normal)
Image Width                     : 600
Image Height                    : 600

Encoding Process                : Progressive DCT, Huffman coding

Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:4:4 (1 1)
Image Size                      : 600x600
Megapixels                      : 0.360
```

**Comment by edelstahlratte** [comment]
Same with the `file` command:

`AlbumArt2.jpg: JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=1, orientation=upper-left], progressive, precision 8, 600x600, components 3`

**Comment by desbma** [comment]
I get different outputs for `exiftool`:
```
ExifTool Version Number         : 12.60
File Name                       : cGVn.jpeg
Directory                       : /home/maxime/Downloads
File Size                       : 193 kB
File Modification Date/Time     : 2023:07:01 21:44:06+02:00
File Access Date/Time           : 2023:07:01 21:44:06+02:00
File Inode Change Date/Time     : 2023:07:01 21:44:06+02:00
File Permissions                : -rw-r--r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Exif Byte Order                 : Little-endian (Intel, II)
Orientation                     : Horizontal (normal)
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Exif Image Width                : 600
Exif Image Height               : 600
Image Width                     : 600
Image Height                    : 600
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:4:4 (1 1)
Image Size                      : 600x600
Megapixels                      : 0.360
```

And `file`:
```
JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=5, orientation=upper-left, xresolution=74, yresolution=82, resolutionunit=2], baseline, precision 8, 600x600, components 3
```

Can you upload your file, so we are sure we are looking at the same thing?

**Comment by edelstahlratte** [comment]
Hello,

this is the file directly from the Discogs URl above..

[picture.zip](https://github.com/desbma/sacad/files/11957702/picture.zip)

**Comment by desbma** [comment]
Interesting !

If you download https://i.discogs.com/PmIViK7oa7birbtqlJUnBezsLz7lYBwcQKxM7Efk52w/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMxODkt/MTE3MTQzMzgxNy5q/cGVn.jpeg from a browser you will get a progressive JPEG as a response.

If you download that URL with `curl` or from `sacad`, you will **not** get a progressive JPEG however.

Discogs is probably using the user agent to conditionally serve the progressive version to clients that support it.

Can you confirm the JPEG is **not** progressive when downloading with Sacad?

**Comment by edelstahlratte** [comment]
No, by using sacad_r I got about 3 progressive images out of 30... That's why I wrote the issue in the first place... 

`curl --output test.jpg https://i.discogs.com/PmIViK7oa7birbtqlJUnBezsLz7lYBwcQKxM7Efk52w/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMxODkt/MTE3MTQzMzgxNy5q/cGVn.jpeg
`

gives me a progressive jpeg.

Strangely 

`sacad -sdiscogs "Meat Beat Manifesto" "Subliminal Sandwich" 600 AlbumArtDiscogs.jpg`

gives me **today** a non progressive jpeg, but with another URL:

`https://i.discogs.com/w7z7D72ZqYTOZSxn1uWBkqgyi6SKdVlvyrkjzuA-7Zg/rs:fit/g:sm/q:90/h:594/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM0ODY2/OTYtMTY3Njc0NDQ1/OS0yODY3LmpwZWc.jpeg`

**Comment by desbma** [comment]
Here is the non progressive image I get 
![cGVn](https://github.com/desbma/sacad/assets/1145175/9b05d37e-8ea1-42f4-af4d-d1ca1944bf6d)

**Comment by desbma** [comment]
What is even weirder is that the progressive file is **smaller**, so I'm not sure it makes sense to try to make a non progressive variant.

Do you have any reason to avoid progressive JPEG apart from size?

**Comment by edelstahlratte** [comment]
Not all Music Players can handle progressive JPEGs esp. the Sony Players (which I use) are known for not showing progressive album art jpeg files...

**Comment by desbma** [comment]
Can you try 836a1ae90b891370b8a475414ce47e92b597967f from the `progressive-jpeg` branch?

**Comment by edelstahlratte** [comment]
Hello, 

sorry for the late response... Finally got some new CDs (abt. 30)... All files have been baseline using the new '--convert-progressive-jpeg' option!

So, seems to work...

Thank you very much!

**Comment by desbma** [comment]
Great
