### ISSUE TITLE
Removing space from tags in output filename

### ISSUE THREAD

**Issue by Cassian-Andor** [desbma/sacad#91]
I think around [here](https://github.com/desbma/sacad/blob/a1a8084d20a183c59bf6b75be71fac1d2c73c8d6/sacad/recurse.py#L176) spaces in output filenames are deleted. May I ask why is that so? Possible to make it optional?

I have a script that does something like this
`acad_r "${1}" 6000 "{artist} - {album} - Front.png"`
But then if the artist is `The Beatles`, in the filename it's `TheBeatles`, same for albums. Which is kind of a moot point because I can introduce a space anyway in the filename format.

**Comment by desbma** [comment]
It should be fixed now.
