### ISSUE TITLE
[Request] Artist Cover?

### ISSUE THREAD

**Issue by Cassian-Andor** [desbma/sacad#92]
Are there any plans to add an option to download Artist Cover Art? Useful for self-hosted servers like Jellyfin or Subsonic that can read this. I assume that since the usage of common APIs is in place, searching for Artist Covers instead of Albums shouldn't be so difficult?

**Comment by desbma** [comment]
I have currently no plan to implement that.

At some point in the future, I would like to completely rewrite the code, and I might implement that at that time, but that is when and if I have time to do that (certainly not this year), so don't hold your breath...
