### ISSUE TITLE
Where i put the command line in the code?

### ISSUE THREAD

**Issue by dsenff1979** [desbma/sacad#94]
Hi, i'm start learn python

Where i put in the code the command: sacad "metallica" "master of puppets" 600 AlbumArt.jpg
or this command sacad_r library_directory 600 AlbumArt.jpg?
Can you give me a exemple with the complete code?

import sacad

if __name__ == "__main__":

  sacad.cl_main()

**Comment by desbma** [comment]
You can either use sacad as a command line tool, or from Python code as a library.

 `sacad "metallica" "master of puppets" 600 AlbumArt.jpg` or `sacad_r library_directory 600 AlbumArt.jpg` are command lines, please search for tutorials or other source of help for beginners, for how to run command lines in your system.
