### ISSUE TITLE
`--ignore-existing` in `sacad_r` reports 'no result found' when cover.jpg is present in the folder within the size tolerance

### ISSUE THREAD

**Issue by shipurjan** [desbma/sacad#97]
In my opinion the program should first check whether the folder contains the filename provided and if its within given tolerance, before looking it up online. It's a little bit confusing how albums with cover present are still reported as not having them.

And to clarify, the source of cover.jpg is not sacad sources, it's from somewhere else

By the way it's a great program and saves a ton of time :)

**Comment by desbma** [comment]
I'm not sure I understand what is the issue.
`--ignore-existing` makes `sacad_r` *not* look at the existing files.

> In my opinion the program should first check whether the folder contains the filename provided and if its within given tolerance, before looking it up online.

That is the default behavior without `--ignore-existing`.

**Comment by shipurjan** [comment]
Oh sorry, I was a little sleep deprived when I made this issue, I didn't understand this flag correctly. My bad, unnecessary issue.
